name: microblogging
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  mobx: ^2.0.7+5
  build_runner: ^2.2.0
  mobx_codegen: ^2.0.7
  flutter_mobx: ^2.0.6+1
  date_format: ^2.0.6
  another_flushbar: ^1.10.29
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
      - assets/images/

  fonts:
      - family: Lato
        fonts:
          - asset: assets/fonts/Lato-Regular.ttf
